# Config file for automatic testing at travis-ci.org

language: python
python:
  - '3.6'
  - '2.7'

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  # https://setuptools.readthedocs.io/en/latest/history.html#id228
  # https://github.com/pypa/setuptools_scm/blob/main/CHANGELOG.rst#v600
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install "setuptools<45" "setuptools_scm<6"; fi
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

jobs:
  include:
    - stage: lambda
      language: python
      python: '3.6'
      before_script: cd cloudformation
      script: tox
